### ISSUE TITLE
investigate failed tests: test_cooperatives, tenders/test_parse_data.py

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-data-pipelines#82]
looks like test_parse_data failure was introduced [here](https://travis-ci.org/OpenBudget/budgetkey-data-pipelines/builds/279137913)

and test_cooperatives failure was introduced [here](https://travis-ci.org/OpenBudget/budgetkey-data-pipelines/builds/281867476)

**Comment by akariv** [comment]
Thanks for keeping an eye on these.

parse_data was modified so that tender_id won't get empty strings (which
are later converted to None), as it's a part of the primary key in the DB
so cannot be null.
cooperatives was modified as its internal self.parse_date was failing on
missing dates in the original data, so I opted to use the tableschema for
that instead of rewriting a date parser.

You can assign this issue to me so I can fix the tests, as it's my bad
(should be easy fixes).
