### ISSUE TITLE
association_annual_turnover not collected

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-data-pipelines#95]
- this is מחזור שנתי
- sample organisation where it's showing: http://www.guidestar.org.il/GS_Malkar?number=580294940
- processor is called 'guidestar'

**Comment by gidgid** [comment]
It seems like every value that relies on these IDs is not stable and is not saved in the DB. Even values like "proper management" are not saved due to changing IDs

For example "gov-bits" currently relies on id (in the actual code): 620 but when I looked at it the id was: 649

Not sure if its solid enough but it seems like: each ".gov-field views-field views-field-field-gov-objectives has-text" tag has a child " comp-header" tag (the space is intentional). If it has this tag child it should extract the values from the other child tags: "field-content"

**Comment by noamoss** [comment]
@akariv please add the commit and close.

**Comment by akariv** [comment]
https://github.com/OpenBudget/budgetkey-data-pipelines/commit/5918ed7b77c0f4343e2ae359650136a4aeed0833
